# Generated by Django 6.0.1 on 2026-01-18 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_konta', models.CharField(max_length=26, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status_konta', models.CharField(choices=[('aktywne', 'Aktywne'), ('zablokowane', 'Zablokowane')], default='aktywne', max_length=11)),
                ('wlasciciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Przelew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(default='Przelew krajowy', max_length=50)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('nadawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wychodzace', to='bank.konto')),
                ('odbiorca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='przychodzace', to='bank.konto')),
            ],
        ),
    ]
